-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 11:27:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gestion_conocimiento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gestion_conocimiento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestion_conocimiento` DEFAULT CHARACTER SET utf8 ;
USE `Gestion_conocimiento` ;

-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Persona` (
  `id_perso` INT NOT NULL,
  `nom_perso` VARCHAR(45) NULL,
  `cc_perso` INT NULL,
  `fecha_naci` INT NULL,gestion_conocimiento
  PRIMARY KEY (`id_perso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Perfil` (
  `id_perfil` INT NOT NULL,
  `nom_perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Departamento` (
  `id_departa` INT NOT NULL,
  `nom_departa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_departa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Area` (
  `id_area` INT NOT NULL,
  `nom_area` VARCHAR(45) NULL,
  `Departamento_id_departa` INT NOT NULL,
  PRIMARY KEY (`id_area`),
  INDEX `fk_Area_Departamento1_idx` (`Departamento_id_departa` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Departamento1`
    FOREIGN KEY (`Departamento_id_departa`)
    REFERENCES `Gestion_conocimiento`.`Departamento` (`id_departa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Funciones` (
  `id_funcion` INT NOT NULL,
  `nom_funcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`actividad` (
  `id_activi` INT NOT NULL,
  `nom_activi` VARCHAR(45) NULL COMMENT 'nombre de los procedimientos= actividad ',
  `descrip_activi` VARCHAR(45) NULL,
  `url_infograma` VARCHAR(45) NULL,
  `url_ova` VARCHAR(45) NULL,
  PRIMARY KEY (`id_activi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`tipo_documento` (
  `id_tipo_docu` INT NOT NULL,
  `nom_tipo_docu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_docu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`documentos` (
  `id_docum` INT NOT NULL,
  `codigo_docum` VARCHAR(45) NULL,
  `nom_docum` VARCHAR(45) NULL,
  `actividad_id_activi` INT NOT NULL,
  `tipo_documento_id_tipo_docu` INT NOT NULL,
  PRIMARY KEY (`id_docum`),
  INDEX `fk_documentos_actividad1_idx` (`actividad_id_activi` ASC) VISIBLE,
  INDEX `fk_documentos_tipo_documento1_idx` (`tipo_documento_id_tipo_docu` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_actividad1`
    FOREIGN KEY (`actividad_id_activi`)
    REFERENCES `Gestion_conocimiento`.`actividad` (`id_activi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id_tipo_docu`)
    REFERENCES `Gestion_conocimiento`.`tipo_documento` (`id_tipo_docu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`competencia` (
  `id_compe` INT NOT NULL,
  `nom_compe` VARCHAR(45) NULL,
  `descrip_compe` VARCHAR(45) NULL,
  `nivel_aceptacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_compe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`pag_amarilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`pag_amarilla` (
  `id_pag_amarilla` INT NOT NULL,
  `nom_pag` VARCHAR(45) NULL,
  `descrip_pag` VARCHAR(45) NULL,
  `url_ova_pag` VARCHAR(45) NULL,
  `ico_pag` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pag_amarilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Persona_has_competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Persona_has_competencia` (
  `Persona_id_perso` INT NOT NULL,
  `competencia_id_compe` INT NOT NULL,
  `fecha_compe` VARCHAR(45) NULL,
  `nota_compete` VARCHAR(45) NULL,
  `verficacion` TINYBLOB NULL,
  PRIMARY KEY (`Persona_id_perso`, `competencia_id_compe`),
  INDEX `fk_Persona_has_competencia_competencia1_idx` (`competencia_id_compe` ASC) VISIBLE,
  INDEX `fk_Persona_has_competencia_Persona_idx` (`Persona_id_perso` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_has_competencia_Persona`
    FOREIGN KEY (`Persona_id_perso`)
    REFERENCES `Gestion_conocimiento`.`Persona` (`id_perso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_competencia_competencia1`
    FOREIGN KEY (`competencia_id_compe`)
    REFERENCES `Gestion_conocimiento`.`competencia` (`id_compe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Perfil_has_Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Perfil_has_Area` (
  `Perfil_id_perfil` INT NOT NULL,
  `Area_id_area` INT NOT NULL,
  `nivel_perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`Perfil_id_perfil`, `Area_id_area`),
  INDEX `fk_Perfil_has_Area_Area1_idx` (`Area_id_area` ASC) VISIBLE,
  INDEX `fk_Perfil_has_Area_Perfil1_idx` (`Perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_has_Area_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `Gestion_conocimiento`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_Area_Area1`
    FOREIGN KEY (`Area_id_area`)
    REFERENCES `Gestion_conocimiento`.`Area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`user` (
  `id_user` INT NOT NULL,
  `email_user` VARCHAR(45) NULL,
  `Persona_id_perso` INT NOT NULL,
  `Perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_user`, `Persona_id_perso`),
  INDEX `fk_user_Persona1_idx` (`Persona_id_perso` ASC) VISIBLE,
  INDEX `fk_user_Perfil1_idx` (`Perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_user_Persona1`
    FOREIGN KEY (`Persona_id_perso`)
    REFERENCES `Gestion_conocimiento`.`Persona` (`id_perso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `Gestion_conocimiento`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Perfil_has_Funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Perfil_has_Funciones` (
  `Perfil_id_perfil` INT NOT NULL,
  `Funciones_id_funcion` INT NOT NULL,
  PRIMARY KEY (`Perfil_id_perfil`, `Funciones_id_funcion`),
  INDEX `fk_Perfil_has_Funciones_Funciones1_idx` (`Funciones_id_funcion` ASC) VISIBLE,
  INDEX `fk_Perfil_has_Funciones_Perfil1_idx` (`Perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_has_Funciones_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `Gestion_conocimiento`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_Funciones_Funciones1`
    FOREIGN KEY (`Funciones_id_funcion`)
    REFERENCES `Gestion_conocimiento`.`Funciones` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Indicadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Indicadores` (
  `id_indica` INT NOT NULL,
  `nom_indica` VARCHAR(45) NULL,
  `meta_indica` VARCHAR(45) NULL,
  PRIMARY KEY (`id_indica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Departamento_has_Indicadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Departamento_has_Indicadores` (
  `Departamento_id_departa` INT NOT NULL,
  `Indicadores_id_indica` INT NOT NULL,
  `fecha_inicial` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `actual_estado` VARCHAR(45) NULL,
  `final_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`Departamento_id_departa`, `Indicadores_id_indica`),
  INDEX `fk_Departamento_has_Indicadores_Indicadores1_idx` (`Indicadores_id_indica` ASC) VISIBLE,
  INDEX `fk_Departamento_has_Indicadores_Departamento1_idx` (`Departamento_id_departa` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_has_Indicadores_Departamento1`
    FOREIGN KEY (`Departamento_id_departa`)
    REFERENCES `Gestion_conocimiento`.`Departamento` (`id_departa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_has_Indicadores_Indicadores1`
    FOREIGN KEY (`Indicadores_id_indica`)
    REFERENCES `Gestion_conocimiento`.`Indicadores` (`id_indica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Departamento_has_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Departamento_has_actividad` (
  `Departamento_id_departa` INT NOT NULL,
  `actividad_id_activi` INT NOT NULL,
  PRIMARY KEY (`Departamento_id_departa`, `actividad_id_activi`),
  INDEX `fk_Departamento_has_actividad_actividad1_idx` (`actividad_id_activi` ASC) VISIBLE,
  INDEX `fk_Departamento_has_actividad_Departamento1_idx` (`Departamento_id_departa` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_has_actividad_Departamento1`
    FOREIGN KEY (`Departamento_id_departa`)
    REFERENCES `Gestion_conocimiento`.`Departamento` (`id_departa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_has_actividad_actividad1`
    FOREIGN KEY (`actividad_id_activi`)
    REFERENCES `Gestion_conocimiento`.`actividad` (`id_activi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`menu` (
  `id_menu` INT NOT NULL,
  `nom_menu` VARCHAR(45) NULL,
  `url_menu` VARCHAR(45) NULL,
  `icono_menu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestion_conocimiento`.`Perfil_has_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_conocimiento`.`Perfil_has_menu` (
  `Perfil_id_perfil` INT NOT NULL,
  `menu_id_menu` INT NOT NULL,
  `date_menu` VARCHAR(45) NULL,
  PRIMARY KEY (`Perfil_id_perfil`, `menu_id_menu`),
  INDEX `fk_Perfil_has_menu_menu1_idx` (`menu_id_menu` ASC) VISIBLE,
  INDEX `fk_Perfil_has_menu_Perfil1_idx` (`Perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_Perfil_has_menu_Perfil1`
    FOREIGN KEY (`Perfil_id_perfil`)
    REFERENCES `Gestion_conocimiento`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_menu_menu1`
    FOREIGN KEY (`menu_id_menu`)
    REFERENCES `Gestion_conocimiento`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
